/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectjerusalen;

import BusinessLogic.compraLogic;
import BusinessLogic.sesion;
import java.text.DateFormat;
import java.text.ParseException;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import rojeru_san.RSMTextFull;


public class frmCompra extends javax.swing.JFrame {
    ///Formato de la fecha
    Locale loc = new Locale("es", "SV");
    DateFormat dateFormat = DateFormat.getDateInstance(DateFormat.DEFAULT, loc);
    
    compraLogic cmp = new compraLogic(); 
    public frmCompra() {
        initComponents();
        aumentarid();
        llenarProveedor();
        llenarUsuario();
        llenarFecha();
        llenarTipo();
        txtCantidad.setText("0");
    }
    private void aumentarid()
    {
        int id;
        id = cmp.extraerIdCompra();
        txtIdCompra.setText(id + "");
    }
    private void llenarProveedor()
    {
        cmp.llenarproveedor(cmbProveedor);
    }
    private void llenarUsuario()
    {
        cmp.llenarUsuario(txtUsuario);
    }
    private void llenarFecha()
    {
        String date = dateFormat.format(new Date());
        txtFecha.setText(date);
        txtFecha.disable();
    }
    private void llenarTipo()
    {
        cmp.llenarTipoCompra(cmbTipoCompra);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelShadow1 = new rojeru_san.RSPanelShadow();
        jPanel1 = new javax.swing.JPanel();
        btnCerrar = new rojeru_san.RSButtonRiple();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCompra = new javax.swing.JTable();
        btnCancelar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtIdCompra = new rojeru_san.RSMTextFull();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cmbTipoCompra = new javax.swing.JComboBox<>();
        txtUsuario = new rojeru_san.RSMTextFull();
        txtFecha = new rojeru_san.RSMTextFull();
        cmbProveedor = new javax.swing.JComboBox<>();
        btnBusProveedor = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtDescripcion = new rojeru_san.RSMTextFull();
        jLabel13 = new javax.swing.JLabel();
        txtCantidad = new rojeru_san.RSMTextFull();
        jLabel14 = new javax.swing.JLabel();
        txtProducto = new rojeru_san.RSMTextFull();
        jLabel15 = new javax.swing.JLabel();
        txtPrecio = new rojeru_san.RSMTextFull();
        btnBuscarPro = new javax.swing.JButton();
        txtLote = new rojeru_san.RSMTextFull();
        jLabel17 = new javax.swing.JLabel();
        txtPrecioVenta = new rojeru_san.RSMTextFull();
        jLabel18 = new javax.swing.JLabel();
        txtTotalCompra = new rojeru_san.RSMTextFull();
        btnGuardar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(22, 33, 62));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrar.setBackground(new java.awt.Color(22, 33, 62));
        btnCerrar.setBorder(null);
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elements/cerrar.png"))); // NOI18N
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 40, 44, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("COMPRA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, -1, -1));

        tableCompra.setBackground(new java.awt.Color(45, 55, 99));
        tableCompra.setForeground(new java.awt.Color(255, 255, 255));
        tableCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Factura", "Id Producto", "Producto", "Descripcion", "Cantidad", "Precio Compra", "IVA", "Subtotal", "Precio Venta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableCompra.setFocusable(false);
        tableCompra.setGridColor(new java.awt.Color(153, 153, 153));
        tableCompra.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tableCompra.setRowHeight(25);
        tableCompra.setSelectionBackground(new java.awt.Color(47, 63, 128));
        tableCompra.setShowVerticalLines(false);
        tableCompra.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableCompra);
        if (tableCompra.getColumnModel().getColumnCount() > 0) {
            tableCompra.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 940, 150));

        btnCancelar.setBackground(new java.awt.Color(26, 26, 46));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(233, 69, 96)));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 640, 150, 40));

        btnEliminar.setBackground(new java.awt.Color(26, 26, 46));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(233, 69, 96)));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 334, 110, 70));

        jPanel2.setBackground(new java.awt.Color(22, 33, 62));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white), "Datos de Compra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setName(""); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fecha:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        txtIdCompra.setBackground(new java.awt.Color(22, 33, 62));
        txtIdCompra.setForeground(new java.awt.Color(255, 255, 255));
        txtIdCompra.setBordeColorFocus(new java.awt.Color(255, 255, 255));
        txtIdCompra.setBotonColor(new java.awt.Color(255, 255, 255));
        txtIdCompra.setPlaceholder("");
        jPanel2.add(txtIdCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 80, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Usuario:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ID Compra");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Proveedor:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tipo de Compra:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, -1, -1));

        jPanel2.add(cmbTipoCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 40, 220, -1));

        txtUsuario.setBackground(new java.awt.Color(22, 33, 62));
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.setBordeColorFocus(new java.awt.Color(255, 255, 255));
        txtUsuario.setBotonColor(new java.awt.Color(255, 255, 255));
        txtUsuario.setPlaceholder("");
        jPanel2.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 220, -1));

        txtFecha.setBackground(new java.awt.Color(22, 33, 62));
        txtFecha.setForeground(new java.awt.Color(255, 255, 255));
        txtFecha.setBordeColorFocus(new java.awt.Color(255, 255, 255));
        txtFecha.setBotonColor(new java.awt.Color(255, 255, 255));
        txtFecha.setPlaceholder("");
        jPanel2.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 180, -1));

        jPanel2.add(cmbProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 240, -1));

        btnBusProveedor.setBackground(new java.awt.Color(26, 26, 46));
        btnBusProveedor.setForeground(new java.awt.Color(255, 255, 255));
        btnBusProveedor.setText("Buscar");
        btnBusProveedor.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(233, 69, 96)));
        jPanel2.add(btnBusProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, 90, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 940, 140));

        btnAgregar.setBackground(new java.awt.Color(26, 26, 46));
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(233, 69, 96)));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 250, 110, 70));

        jPanel4.setBackground(new java.awt.Color(22, 33, 62));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white), "Datos del articulo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.setName(""); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cantidad:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, -1, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Producto:");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        txtDescripcion.setBackground(new java.awt.Color(22, 33, 62));
        txtDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        txtDescripcion.setBordeColorFocus(new java.awt.Color(255, 255, 255));
        txtDescripcion.setBotonColor(new java.awt.Color(255, 255, 255));
        txtDescripcion.setPlaceholder("");
        jPanel4.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 240, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Lote:");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, -1, -1));

        txtCantidad.setBackground(new java.awt.Color(22, 33, 62));
        txtCantidad.setForeground(new java.awt.Color(255, 255, 255));
        txtCantidad.setBordeColorFocus(new java.awt.Color(255, 255, 255));
        txtCantidad.setBotonColor(new java.awt.Color(255, 255, 255));
        txtCantidad.setPlaceholder("");
        jPanel4.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, 130, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Descripcion:");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        txtProducto.setBackground(new java.awt.Color(22, 33, 62));
        txtProducto.setForeground(new java.awt.Color(255, 255, 255));
        txtProducto.setBordeColorFocus(new java.awt.Color(255, 255, 255));
        txtProducto.setBotonColor(new java.awt.Color(255, 255, 255));
        txtProducto.setPlaceholder("");
        jPanel4.add(txtProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 260, -1));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Precio Compra:");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 140, -1));

        txtPrecio.setBackground(new java.awt.Color(22, 33, 62));
        txtPrecio.setForeground(new java.awt.Color(255, 255, 255));
        txtPrecio.setBordeColorFocus(new java.awt.Color(255, 255, 255));
        txtPrecio.setBotonColor(new java.awt.Color(255, 255, 255));
        txtPrecio.setPlaceholder("");
        jPanel4.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 220, -1));

        btnBuscarPro.setBackground(new java.awt.Color(26, 26, 46));
        btnBuscarPro.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarPro.setText("Buscar");
        btnBuscarPro.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(233, 69, 96)));
        btnBuscarPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProActionPerformed(evt);
            }
        });
        jPanel4.add(btnBuscarPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 90, 40));

        txtLote.setBackground(new java.awt.Color(22, 33, 62));
        txtLote.setForeground(new java.awt.Color(255, 255, 255));
        txtLote.setBordeColorFocus(new java.awt.Color(255, 255, 255));
        txtLote.setBotonColor(new java.awt.Color(255, 255, 255));
        txtLote.setPlaceholder("");
        jPanel4.add(txtLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 200, -1));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Precio Venta:");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, -1, -1));

        txtPrecioVenta.setBackground(new java.awt.Color(22, 33, 62));
        txtPrecioVenta.setForeground(new java.awt.Color(255, 255, 255));
        txtPrecioVenta.setBordeColorFocus(new java.awt.Color(255, 255, 255));
        txtPrecioVenta.setBotonColor(new java.awt.Color(255, 255, 255));
        txtPrecioVenta.setPlaceholder("");
        jPanel4.add(txtPrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 250, -1));

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("IVA:      13%");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 110, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 820, 220));

        txtTotalCompra.setBackground(new java.awt.Color(22, 33, 62));
        txtTotalCompra.setForeground(new java.awt.Color(255, 255, 255));
        txtTotalCompra.setBordeColorFocus(new java.awt.Color(255, 255, 255));
        txtTotalCompra.setBotonColor(new java.awt.Color(255, 255, 255));
        txtTotalCompra.setPlaceholder("");
        jPanel1.add(txtTotalCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 630, 150, -1));

        btnGuardar.setBackground(new java.awt.Color(26, 26, 46));
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(233, 69, 96)));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 640, 150, 40));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Total:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 640, -1, -1));

        rSPanelShadow1.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(rSPanelShadow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -10, 1190, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();

    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnBuscarProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProActionPerformed
        ///Abrir el formulario productos
        sesion.CProducto = "VoyDeCompra";
        frmProduct men = new frmProduct(txtProducto, txtDescripcion, txtLote);
        men.setVisible(true);
    }//GEN-LAST:event_btnBuscarProActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        //Agregar datos a la tabla
        int fact = Integer.parseInt(txtIdCompra.getText());
        String prod = txtProducto.getText();
        String desc = txtDescripcion.getText();
        int cant = Integer.parseInt(txtCantidad.getText());
        double prec = Double.parseDouble(txtPrecio.getText());
        double precVenta = Double.parseDouble(txtPrecioVenta.getText().toString());
        if(prod.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un productos");
        }
        else if(cant == 0)
        {
            JOptionPane.showMessageDialog(null, "No pude agregar la cantidad de 0 productos");
        }
        else if(prec == 0)
        {
            JOptionPane.showMessageDialog(null, "El producto debe tener un precio");
        }
        else{
            cmp.llenarTabla(fact, prod, desc, cant, prec, precVenta,tableCompra, txtTotalCompra);
        }        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            boolean valor;
            int idCompra = Integer.parseInt(txtIdCompra.getText().toString());
            int idProveedor = cmbProveedor.getSelectedIndex();
            int idTipo = cmbTipoCompra.getSelectedIndex();
            Date fecha = dateFormat.parse(txtFecha.getText());
            double total = Double.parseDouble(txtTotalCompra.getText());
            valor = cmp.ingresarCompra(idCompra, idProveedor, idTipo, fecha, total);
            if(valor == true)
            {
                boolean valor2;
                valor2 = cmp.ingresarDetalleCompra(tableCompra);
                if(valor2 == true)
                {
                    JOptionPane.showMessageDialog(null, "Compra hecha correctamente");
                }
                else{
                    JOptionPane.showMessageDialog(null, "No se pudo ingresar el detalle de compra");
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "No se pudo ingresar la compra");
            }
        } catch (ParseException ex) {
            Logger.getLogger(frmCompra.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        cmp.eliminardetabla(tableCompra);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        txtDescripcion.setText("");
        txtCantidad.setText("0");
        txtLote.setText("0");
        txtPrecio.setText("0");
        txtPrecioVenta.setText("0");
        txtProducto.setText("");
        txtTotalCompra.setText("");
        cmbProveedor.setSelectedIndex(0);
        cmbTipoCompra.setSelectedIndex(0);
        cmp.limpiarTabla(tableCompra);
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBusProveedor;
    private javax.swing.JButton btnBuscarPro;
    private javax.swing.JButton btnCancelar;
    private rojeru_san.RSButtonRiple btnCerrar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbProveedor;
    private javax.swing.JComboBox<String> cmbTipoCompra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private rojeru_san.RSPanelShadow rSPanelShadow1;
    private javax.swing.JTable tableCompra;
    private rojeru_san.RSMTextFull txtCantidad;
    private rojeru_san.RSMTextFull txtDescripcion;
    private rojeru_san.RSMTextFull txtFecha;
    private rojeru_san.RSMTextFull txtIdCompra;
    private rojeru_san.RSMTextFull txtLote;
    private rojeru_san.RSMTextFull txtPrecio;
    private rojeru_san.RSMTextFull txtPrecioVenta;
    private rojeru_san.RSMTextFull txtProducto;
    private rojeru_san.RSMTextFull txtTotalCompra;
    private rojeru_san.RSMTextFull txtUsuario;
    // End of variables declaration//GEN-END:variables
}
