/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectjerusalen;

import BusinessLogic.ClientesLogic;
import BusinessLogic.sesion;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author Erick Siguache
 */
public class frmClient extends javax.swing.JFrame {

    private ClientesLogic ClieLog = new ClientesLogic();
    int idClientes=-1;
    
    public frmClient() {
        initComponents();
        mostrarClientes();
        
        
        
        //Con esto simulamos un textChanged 
        //Para asi cuando borramos todo lo del nombre se vuelva a listar todo
        txtNombre.addKeyListener(new KeyListener() {
        @Override
        public void keyTyped(KeyEvent arg0) {
            if(txtNombre.getText().isEmpty())
            {
                mostrarClientes();
            }
        }
        @Override
        public void keyReleased(KeyEvent arg0) {
            if(txtNombre.getText().isEmpty())
            {
                mostrarClientes();
            }
        }
        @Override
        public void keyPressed(KeyEvent arg0) {
            if(txtNombre.getText().isEmpty())
            {
                mostrarClientes();
            }
        }
    });
    }
    ///Sobrecargando el formulario
    JTextField idCli;
    JTextField nombreCli;
    public frmClient(JTextField id, JTextField nombre)
    {
        initComponents();
        mostrarClientes();
        idCli = id;
        nombreCli = nombre;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelShadow1 = new rojeru_san.RSPanelShadow();
        jPanel1 = new javax.swing.JPanel();
        btnCerrar = new rojeru_san.RSButtonRiple();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDireccion = new rojeru_san.RSMTextFull();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new rojeru_san.RSMTextFull();
        txtApellido = new rojeru_san.RSMTextFull();
        txtTelefono = new rojeru_san.RSMTextFull();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableClient = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1140, 680));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(22, 33, 62));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrar.setBackground(new java.awt.Color(22, 33, 62));
        btnCerrar.setBorder(null);
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elements/cerrar.png"))); // NOI18N
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 40, 44, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CLIENTES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Direccion:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, -1, -1));

        txtDireccion.setBackground(new java.awt.Color(22, 33, 62));
        txtDireccion.setForeground(new java.awt.Color(255, 255, 255));
        txtDireccion.setBordeColorFocus(new java.awt.Color(255, 255, 255));
        txtDireccion.setBotonColor(new java.awt.Color(255, 255, 255));
        txtDireccion.setPlaceholder("");
        jPanel1.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 440, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Apellido:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Telefono:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        txtNombre.setBackground(new java.awt.Color(22, 33, 62));
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.setBordeColorFocus(new java.awt.Color(255, 255, 255));
        txtNombre.setBotonColor(new java.awt.Color(255, 255, 255));
        txtNombre.setPlaceholder("");
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreMouseClicked(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 440, -1));

        txtApellido.setBackground(new java.awt.Color(22, 33, 62));
        txtApellido.setForeground(new java.awt.Color(255, 255, 255));
        txtApellido.setBordeColorFocus(new java.awt.Color(255, 255, 255));
        txtApellido.setBotonColor(new java.awt.Color(255, 255, 255));
        txtApellido.setPlaceholder("");
        txtApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtApellidoMouseClicked(evt);
            }
        });
        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 440, -1));

        txtTelefono.setBackground(new java.awt.Color(22, 33, 62));
        txtTelefono.setForeground(new java.awt.Color(255, 255, 255));
        txtTelefono.setBordeColorFocus(new java.awt.Color(255, 255, 255));
        txtTelefono.setBotonColor(new java.awt.Color(255, 255, 255));
        txtTelefono.setPlaceholder("");
        txtTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTelefonoMouseClicked(evt);
            }
        });
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 260, -1));

        tableClient =new JTable()
        {
            public boolean isCellEditable(int row, int column)
            {
                for (int i = 0; 1< tableClient.getRowCount(); i++)
                {
                    if(row == i)
                    {
                        return false;
                    }
                }
                return true;
            }
        };
        tableClient.setBackground(new java.awt.Color(45, 55, 99));
        tableClient.setForeground(new java.awt.Color(255, 255, 255));
        tableClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Apellido", "Telefono", "Direccion"
            }
        ));
        tableClient.setFocusable(false);
        tableClient.setGridColor(new java.awt.Color(153, 153, 153));
        tableClient.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tableClient.setRowHeight(25);
        tableClient.setSelectionBackground(new java.awt.Color(47, 63, 128));
        tableClient.setShowVerticalLines(false);
        tableClient.getTableHeader().setReorderingAllowed(false);
        tableClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableClientMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableClient);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 890, 250));

        btnGuardar.setBackground(new java.awt.Color(26, 26, 46));
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(233, 69, 96)));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 170, 150, 40));

        btnEditar.setBackground(new java.awt.Color(26, 26, 46));
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Editar");
        btnEditar.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(233, 69, 96)));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 230, 150, 40));

        btnEliminar.setBackground(new java.awt.Color(26, 26, 46));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(233, 69, 96)));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 290, 150, 40));

        lblNombre.setForeground(new java.awt.Color(233, 69, 96));
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 130, -1, -1));

        lblApellido.setForeground(new java.awt.Color(233, 69, 96));
        jPanel1.add(lblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, -1, -1));

        lblTelefono.setForeground(new java.awt.Color(233, 69, 96));
        jPanel1.add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, -1, -1));

        btnBuscar.setBackground(new java.awt.Color(26, 26, 46));
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elements/search.png"))); // NOI18N
        btnBuscar.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(233, 69, 96)));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 110, 60, 40));

        btnReporte.setBackground(new java.awt.Color(26, 26, 46));
        btnReporte.setForeground(new java.awt.Color(255, 255, 255));
        btnReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elements/report.png"))); // NOI18N
        btnReporte.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(233, 69, 96)));
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });
        jPanel1.add(btnReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 110, 60, 40));

        rSPanelShadow1.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(rSPanelShadow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -10, 1190, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarClientes(){
        ClieLog.ListaClientes(tableClient);
    }
    private void tableClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableClientMouseClicked
        String R = sesion.ventaCliente;
        if(sesion.ventaCliente.equals("VoyDeVenta"))
        {
            if(evt.getClickCount() == 1)
            {
                int select=tableClient.getSelectedRow();
                idClientes=Integer.parseInt(tableClient.getValueAt(select, 0).toString());
                txtNombre.setText(tableClient.getValueAt(select, 1).toString());
                txtApellido.setText(tableClient.getValueAt(select, 2).toString());
                txtTelefono.setText(tableClient.getValueAt(select, 3).toString());
                txtDireccion.setText(tableClient.getValueAt(select, 4).toString());
            }
            else if (evt.getClickCount() == 2)
            {
                int select=tableClient.getSelectedRow();
                sesion.idClienteVenta = Integer.parseInt(tableClient.getValueAt(select, 0).toString());
                idCli.setText(tableClient.getValueAt(select, 0).toString());
                String NombreCompleto = tableClient.getValueAt(select, 1).toString() + " " + tableClient.getValueAt(select, 2).toString();
                nombreCli.setText(NombreCompleto);
                sesion.ventaCliente = "";
                this.dispose();
            }
        }
        else if(sesion.ventaCliente.equals("VoyDeAdministracion"))
        {
            int select=tableClient.getSelectedRow();
            idClientes=Integer.parseInt(tableClient.getValueAt(select, 0).toString());
            txtNombre.setText(tableClient.getValueAt(select, 1).toString());
            txtApellido.setText(tableClient.getValueAt(select, 2).toString());
            txtTelefono.setText(tableClient.getValueAt(select, 3).toString());
            txtDireccion.setText(tableClient.getValueAt(select, 4).toString());

        }    
    }//GEN-LAST:event_tableClientMouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String NameClie= txtNombre.getText();
        String ApellidoClie= txtApellido.getText();
        String TelefonoClie= txtTelefono.getText();
        String DireccionClie= txtDireccion.getText();
        if(NameClie.isEmpty()|ApellidoClie.isEmpty()|TelefonoClie.isEmpty()|DireccionClie.isEmpty()){
            JOptionPane.showMessageDialog(null,"Debe llenar todos los datos");
        }else{
            String mensaje="";
            mensaje=ClieLog.insertarCliente(NameClie,ApellidoClie,TelefonoClie,DireccionClie);
            JOptionPane.showMessageDialog(null,"Se ha guardado correctamente");
            mostrarClientes();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        String NameClie= txtNombre.getText();
        String ApellidoClie= txtApellido.getText();
        String TelefonoClie= txtTelefono.getText();
        String DireccionClie= txtDireccion.getText();
        if(idClientes == -1)
        {
            JOptionPane.showMessageDialog(null, "Debe escoger una categoria para editar");
        }else if(NameClie.isEmpty()|ApellidoClie.isEmpty()|TelefonoClie.isEmpty()|DireccionClie.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "No puede quedar ningun campo vacio");
        }
        else {
            String mensaje = "";
            mensaje=ClieLog.actualizarCliente(idClientes, NameClie,ApellidoClie,TelefonoClie,DireccionClie);
            JOptionPane.showMessageDialog(null, mensaje);
            mostrarClientes();
            idClientes = -1; 
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if(idClientes == -1)
        {
            JOptionPane.showMessageDialog(null, "Debe escoger una categoria para eliminar");
        }
        else if (idClientes > -1 ){
            String mensaje = "";
            mensaje = ClieLog.eliminarCliente(idClientes);
            JOptionPane.showMessageDialog(null, mensaje);
            mostrarClientes();
            idClientes = -1; 
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // Validar que solo escriba letras
        //Esta funcion se encuentra en los eventos del txtApellido en event con el nombre de KeyTyped
        String area ="";
        char validarN = evt.getKeyChar();
        if (Character.isDigit(validarN)) {
            getToolkit().beep();
            evt.consume();
            area = "Por Favor: Ingrese solo letras en el nombre";

            lblNombre.setText(area);
        } else if ((int) evt.getKeyChar() >= 33 && (int) evt.getKeyChar() <= 64
                || (int) evt.getKeyChar() >= 91 && (int) evt.getKeyChar() <= 96
                || (int) evt.getKeyChar() >= 123 && (int) evt.getKeyChar() <= 208
                || (int) evt.getKeyChar() >= 210 && (int) evt.getKeyChar() <= 240
                || (int) evt.getKeyChar() >= 242 && (int) evt.getKeyChar() <= 255) {
            getToolkit().beep();
            evt.consume();
            area = "No se permiten caracteres especiales";
            lblNombre.setText(area);
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
        // Validar que solo escriba letras
        //Esta funcion se encuentra en los eventos del txtApellido en event con el nombre de KeyTyped
        String area ="";
        char validarN = evt.getKeyChar();
        if (Character.isDigit(validarN)) {
            getToolkit().beep();
            evt.consume();
            area = "Por Favor: Ingrese solo letras en el apellido";

            lblApellido.setText(area);
        } else if ((int) evt.getKeyChar() >= 33 && (int) evt.getKeyChar() <= 64
                || (int) evt.getKeyChar() >= 91 && (int) evt.getKeyChar() <= 96
                || (int) evt.getKeyChar() >= 123 && (int) evt.getKeyChar() <= 208
                || (int) evt.getKeyChar() >= 210 && (int) evt.getKeyChar() <= 240
                || (int) evt.getKeyChar() >= 242 && (int) evt.getKeyChar() <= 255) {
            getToolkit().beep();
            evt.consume();
            area = "No se permiten caracteres especiales";
            lblApellido.setText(area);
        }
    }//GEN-LAST:event_txtApellidoKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        // Aqui es para limitar los valores que puede escribir en el jtextfield de telefono a que sean 8 valores
        //Esta funcion se encuentra en los eventos del txtTelefono en event con el nombre de KeyTyped
        String area ="";
        if (txtTelefono.getText().length() >= 8) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
            area = "Por Favor: Ingrese un maximo de 8 numeros en el Telefono";

            lblTelefono.setText(area);
        }
        //Validar que solo se puedan escribir numeros
        char validarN = evt.getKeyChar();
        if (Character.isLetter(validarN)) {
            getToolkit().beep();
            evt.consume();
            area = "Por Favor: Ingrese solo numeros en el Telefono";

            lblTelefono.setText(area);
        } else if ((int) evt.getKeyChar() >= 32 && (int) evt.getKeyChar() <= 47
                || (int) evt.getKeyChar() >= 58 && (int) evt.getKeyChar() <= 255) {
            getToolkit().beep();
            evt.consume();
            area = "Por Favor: Ingrese solo numeros en el Telefono";

            lblTelefono.setText(area);
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMouseClicked
        lblNombre.setText("");
    }//GEN-LAST:event_txtNombreMouseClicked

    private void txtApellidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidoMouseClicked
        lblApellido.setText("");
    }//GEN-LAST:event_txtApellidoMouseClicked

    private void txtTelefonoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelefonoMouseClicked
        lblTelefono.setText("");
    }//GEN-LAST:event_txtTelefonoMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String param = txtNombre.getText();
        ClieLog.buscarPorNombre(param, tableClient);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed

            // TODO add your handling code here:
            ClieLog.ReporteGeneral();
            //ClieLog.xs();
        
    }//GEN-LAST:event_btnReporteActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private rojeru_san.RSButtonRiple btnCerrar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnReporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private rojeru_san.RSPanelShadow rSPanelShadow1;
    private javax.swing.JTable tableClient;
    private rojeru_san.RSMTextFull txtApellido;
    private rojeru_san.RSMTextFull txtDireccion;
    private rojeru_san.RSMTextFull txtNombre;
    private rojeru_san.RSMTextFull txtTelefono;
    // End of variables declaration//GEN-END:variables
}
