/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectjerusalen;

import BusinessLogic.LoginAccess;
import BusinessLogic.sesion;
import Entidad.Usuario;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Erick Siguache
 */
public class frmLogin extends javax.swing.JFrame {

    /**
     * Creates new form frmLogin
     */
    private LoginAccess log = new LoginAccess();

    public frmLogin() {
        initComponents();
        //Linea de llamado del logo y quedo dos que 3 :v
        btnIcono.setIcon(setIcono("/Elements/iconoPri.png", btnIcono));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rSPanelShadow1 = new rojeru_san.RSPanelShadow();
        jPanel2 = new javax.swing.JPanel();
        btnIcono = new rojeru_san.RSButtonRiple();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSalir = new rojeru_san.RSButtonRiple();
        btnMinimizar = new rojeru_san.RSButtonRiple();
        rSPanelShadow2 = new rojeru_san.RSPanelShadow();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtUser = new rojeru_san.RSMTextFull();
        txtPassword = new rojeru_san.RSMTextFull();
        btnIngresar = new rojeru_san.RSButtonRiple();
        txtReestablecer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(22, 33, 62));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIcono.setBackground(new java.awt.Color(22, 33, 62));
        btnIcono.setBorder(null);
        btnIcono.setForeground(new java.awt.Color(22, 33, 62));
        btnIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elements/iconoPri.png"))); // NOI18N
        btnIcono.setColorHover(new java.awt.Color(22, 33, 62));
        btnIcono.setColorTextHover(new java.awt.Color(22, 33, 62));
        btnIcono.setDefaultCapable(false);
        btnIcono.setRippleColor(new java.awt.Color(22, 33, 62));
        jPanel2.add(btnIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 290, 130));

        jLabel1.setBackground(new java.awt.Color(0, 112, 192));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FERRETERIA JERUSALEN");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 310, 50));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ferreteria ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 310, -1));

        rSPanelShadow1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel1.add(rSPanelShadow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 320, 430));

        btnSalir.setBackground(new java.awt.Color(22, 33, 62));
        btnSalir.setBorder(null);
        btnSalir.setText("X");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 40, 30));

        btnMinimizar.setBackground(new java.awt.Color(22, 33, 62));
        btnMinimizar.setBorder(null);
        btnMinimizar.setText("__");
        btnMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizarMouseClicked(evt);
            }
        });
        btnMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 40, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(22, 33, 62));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(22, 33, 62));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("INICIAR SESIÓN");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 380, 40));

        txtUser.setBackground(new java.awt.Color(255, 255, 255));
        txtUser.setForeground(new java.awt.Color(22, 33, 62));
        txtUser.setBordeColorFocus(new java.awt.Color(22, 33, 62));
        txtUser.setBotonColor(new java.awt.Color(22, 33, 62));
        txtUser.setPlaceholder("Nombre de Usuario");
        jPanel3.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 290, -1));

        txtPassword.setBackground(new java.awt.Color(255, 255, 255));
        txtPassword.setForeground(new java.awt.Color(22, 33, 62));
        txtPassword.setBordeColorFocus(new java.awt.Color(22, 33, 62));
        txtPassword.setBotonColor(new java.awt.Color(22, 33, 62));
        txtPassword.setPlaceholder("Contraseña");
        jPanel3.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 290, -1));

        btnIngresar.setBackground(new java.awt.Color(22, 33, 62));
        btnIngresar.setBorder(null);
        btnIngresar.setText("INGRESAR");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jPanel3.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        rSPanelShadow2.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel1.add(rSPanelShadow2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 390, 300));

        txtReestablecer.setBackground(new java.awt.Color(22, 33, 62));
        txtReestablecer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtReestablecer.setForeground(new java.awt.Color(22, 33, 62));
        txtReestablecer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtReestablecer.setText("Reestablecer la contraseña ");
        jPanel1.add(txtReestablecer, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 370, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 410));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Boton de Salida
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        //this.dispose();
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizarActionPerformed
        JFrame frame = new JFrame();
        frame.setResizable(false);
        frame.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }//GEN-LAST:event_btnMinimizarActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        if (txtUser.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese su nombre de usuario");
        } else if (txtPassword.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese su contraseña");
        } else {
            int valor = log.login(txtUser.getText(), txtPassword.getText());
            if (valor == 1) {
                ////AQUI ABRE EL MENU DE ADMINISTRADOR
                log.parasesion(txtUser.getText(), txtPassword.getText());
                frmStartMenu men = new frmStartMenu();
                men.setVisible(true);
                this.dispose();
            }
            else if(valor == 2)
            {
                ////AQUI ABRE EL MENU DEL GERENTE
                log.parasesion(txtUser.getText(), txtPassword.getText());
                frmStartMenu men = new frmStartMenu();
                men.setVisible(true);
                this.dispose();
            }
            else if(valor == 3)
            {
                /////AQUI ABRE EL MENU DEL VENDEDOR
                log.parasesion(txtUser.getText(), txtPassword.getText());
                frmStartMenu men = new frmStartMenu();
                men.setVisible(true);
                this.dispose();
            }
            else {
                JOptionPane.showMessageDialog(null, "Error con el usuario o contraseña");
            }
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizarMouseClicked
        if(evt.getButton()==java.awt.event.MouseEvent.BUTTON1){
            this.setExtendedState(ICONIFIED);
        }
    }//GEN-LAST:event_btnMinimizarMouseClicked

    //Clase para ajustar la imagen al boton
    public Icon setIcono(String url, JButton boton) {
        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        int ancho = boton.getWidth();
        int alto = boton.getHeight();
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));
        return icono;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButtonRiple btnIcono;
    private rojeru_san.RSButtonRiple btnIngresar;
    private rojeru_san.RSButtonRiple btnMinimizar;
    private rojeru_san.RSButtonRiple btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private rojeru_san.RSPanelShadow rSPanelShadow1;
    private rojeru_san.RSPanelShadow rSPanelShadow2;
    private rojeru_san.RSMTextFull txtPassword;
    private javax.swing.JLabel txtReestablecer;
    private rojeru_san.RSMTextFull txtUser;
    // End of variables declaration//GEN-END:variables
}
