/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectjerusalen;

import BusinessLogic.MarcaLogic;
import BusinessLogic.UsersLogic;
import BusinessLogic.lote;

/**
 *
 * @author Josue
 */
public class frmReportes extends javax.swing.JFrame {

    /**
     * Creates new form frmReportes
     */
    MarcaLogic cm = new MarcaLogic();
    lote cmL=new lote();
    UsersLogic cmUser = new UsersLogic();
    
    public frmReportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCerrar = new rojeru_san.RSButtonRiple();
        jLabel1 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        btnProductos = new javax.swing.JButton();
        btnUsuarios1 = new javax.swing.JButton();
        btnCLientes1 = new javax.swing.JButton();
        btnProveedor = new javax.swing.JButton();
        btnLote = new javax.swing.JButton();
        btnProductos1 = new javax.swing.JButton();
        btnProductos2 = new javax.swing.JButton();
        btnMarca1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(22, 33, 62));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrar.setBackground(new java.awt.Color(22, 33, 62));
        btnCerrar.setBorder(null);
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elements/cerrar.png"))); // NOI18N
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 40, 44, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REPORTES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, -1, -1));

        lblNombre.setForeground(new java.awt.Color(233, 69, 96));
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 130, -1, -1));

        lblApellido.setForeground(new java.awt.Color(233, 69, 96));
        jPanel1.add(lblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, -1, -1));

        lblTelefono.setForeground(new java.awt.Color(233, 69, 96));
        jPanel1.add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, -1, -1));

        btnProductos.setBackground(new java.awt.Color(26, 26, 46));
        btnProductos.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnProductos.setForeground(new java.awt.Color(255, 255, 255));
        btnProductos.setText("Venta");
        btnProductos.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(233, 69, 96)));
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        jPanel1.add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 440, 160, 130));

        btnUsuarios1.setBackground(new java.awt.Color(26, 26, 46));
        btnUsuarios1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnUsuarios1.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuarios1.setText("Usuarios");
        btnUsuarios1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(233, 69, 96)));
        btnUsuarios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarios1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnUsuarios1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 160, 130));

        btnCLientes1.setBackground(new java.awt.Color(26, 26, 46));
        btnCLientes1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnCLientes1.setForeground(new java.awt.Color(255, 255, 255));
        btnCLientes1.setText("Clientes");
        btnCLientes1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(233, 69, 96)));
        btnCLientes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCLientes1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnCLientes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 160, 130));

        btnProveedor.setBackground(new java.awt.Color(26, 26, 46));
        btnProveedor.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnProveedor.setForeground(new java.awt.Color(255, 255, 255));
        btnProveedor.setText("Proveedor");
        btnProveedor.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(233, 69, 96)));
        btnProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(btnProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 160, 130));

        btnLote.setBackground(new java.awt.Color(26, 26, 46));
        btnLote.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnLote.setForeground(new java.awt.Color(255, 255, 255));
        btnLote.setText("Lote");
        btnLote.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(233, 69, 96)));
        btnLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoteActionPerformed(evt);
            }
        });
        jPanel1.add(btnLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 440, 160, 130));

        btnProductos1.setBackground(new java.awt.Color(26, 26, 46));
        btnProductos1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnProductos1.setForeground(new java.awt.Color(255, 255, 255));
        btnProductos1.setText("Productos");
        btnProductos1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(233, 69, 96)));
        btnProductos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductos1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnProductos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 150, 160, 130));

        btnProductos2.setBackground(new java.awt.Color(26, 26, 46));
        btnProductos2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnProductos2.setForeground(new java.awt.Color(255, 255, 255));
        btnProductos2.setText("Compra");
        btnProductos2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(233, 69, 96)));
        btnProductos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductos2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnProductos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 150, 160, 130));

        btnMarca1.setBackground(new java.awt.Color(26, 26, 46));
        btnMarca1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnMarca1.setForeground(new java.awt.Color(255, 255, 255));
        btnMarca1.setText("Marca");
        btnMarca1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(233, 69, 96)));
        btnMarca1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarca1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnMarca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 160, 130));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, -6, 1190, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        frmReportesVentas vent= new frmReportesVentas();
        vent.setVisible(true);
        vent.setLocation(240,50);
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnUsuarios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarios1ActionPerformed
        cmUser.ReporteGeneralUsuario();
    }//GEN-LAST:event_btnUsuarios1ActionPerformed

    private void btnCLientes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCLientes1ActionPerformed
        frmReportesClientes ven = new frmReportesClientes();
        ven.setVisible(true);
        ven.setLocation(240,50);
    }//GEN-LAST:event_btnCLientes1ActionPerformed

    private void btnProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedorActionPerformed
        frmReportesProveedor prov = new frmReportesProveedor();
        prov.setVisible(true);
        prov.setLocation(240,50);
    }//GEN-LAST:event_btnProveedorActionPerformed

    private void btnLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoteActionPerformed
        cmL.ReporteGeneralLote();
    }//GEN-LAST:event_btnLoteActionPerformed

    private void btnProductos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductos1ActionPerformed
        frmReportesProductos pro = new frmReportesProductos();
        pro.setVisible(true);
        pro.setLocation(240,50);
    }//GEN-LAST:event_btnProductos1ActionPerformed

    private void btnProductos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductos2ActionPerformed
        frmReportesCompras ven = new frmReportesCompras();
        ven.setVisible(true);
        ven.setLocation(240,50);
    }//GEN-LAST:event_btnProductos2ActionPerformed

    private void btnMarca1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarca1ActionPerformed
        cm.ReporteGeneralMarca();
    }//GEN-LAST:event_btnMarca1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmReportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCLientes1;
    private rojeru_san.RSButtonRiple btnCerrar;
    private javax.swing.JButton btnLote;
    private javax.swing.JButton btnMarca1;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnProductos1;
    private javax.swing.JButton btnProductos2;
    private javax.swing.JButton btnProveedor;
    private javax.swing.JButton btnUsuarios1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    // End of variables declaration//GEN-END:variables
}
