/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectjerusalen;

import BusinessLogic.VentaLogic;
import BusinessLogic.sesion;
import java.text.DateFormat;
import java.text.ParseException;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;



/**
 *
 * @author Erick Siguache
 */
public class frmVenta extends javax.swing.JFrame {
    ///Formato de la fecha
    Locale loc = new Locale("es", "SV");
    DateFormat dateFormat = DateFormat.getDateInstance(DateFormat.DEFAULT, loc);    
    
    VentaLogic vnt = new VentaLogic();
    
    public frmVenta() {
        initComponents();
        llenarTipos();
        aumentarid();
        llenarUsuario();
        llenarFecha();
        txtCantidad.setText("0");
    }
    public void llenarTipos()
    {
        vnt.llenarTipoVent(cmbTipoVenta);
    }
    public void aumentarid()
    {
        int id;
        id = vnt.extraerIdVenta();
        txtNumVenta.setText(id + "");
    }
    public void llenarUsuario()
    {
        vnt.llenarUsuario(txtVendedor);
    }
        private void llenarFecha()
    {
        String date = dateFormat.format(new Date());
        txtFecha.setText(date);
        txtFecha.disable();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelShadow1 = new rojeru_san.RSPanelShadow();
        jPanel1 = new javax.swing.JPanel();
        btnCerrar = new rojeru_san.RSButtonRiple();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableVenta = new javax.swing.JTable();
        btnCancelar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtVendedor = new rojeru_san.RSMTextFull();
        txtNumVenta = new rojeru_san.RSMTextFull();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtFecha = new rojeru_san.RSMTextFull();
        cmbTipoVenta = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        txtBuscarClie = new rojeru_san.RSMTextFull();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNombre = new rojeru_san.RSMTextFull();
        btnBuscarClie = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtProducto = new rojeru_san.RSMTextFull();
        jLabel12 = new javax.swing.JLabel();
        txtCantidad = new rojeru_san.RSMTextFull();
        btnBuscarPro = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtPrecioUni = new rojeru_san.RSMTextFull();
        jLabel14 = new javax.swing.JLabel();
        txtStock = new rojeru_san.RSMTextFull();
        jLabel18 = new javax.swing.JLabel();
        txtTotalVenta = new rojeru_san.RSMTextFull();
        btnGuardar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(22, 33, 62));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrar.setBackground(new java.awt.Color(22, 33, 62));
        btnCerrar.setBorder(null);
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elements/cerrar.png"))); // NOI18N
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 40, 44, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VENTA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, -1, -1));

        tableVenta.setBackground(new java.awt.Color(45, 55, 99));
        tableVenta.setForeground(new java.awt.Color(255, 255, 255));
        tableVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Venta", "idProducto", "Producto", "Precio Unitario", "Cantidad", "IVA", "Subtotal"
            }
        ));
        tableVenta.setFocusable(false);
        tableVenta.setGridColor(new java.awt.Color(153, 153, 153));
        tableVenta.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tableVenta.setRowHeight(25);
        tableVenta.setSelectionBackground(new java.awt.Color(47, 63, 128));
        tableVenta.setShowVerticalLines(false);
        tableVenta.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableVenta);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 960, 150));

        btnCancelar.setBackground(new java.awt.Color(26, 26, 46));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(233, 69, 96)));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 610, 150, 40));

        btnEliminar.setBackground(new java.awt.Color(26, 26, 46));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(233, 69, 96)));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 360, 150, 60));

        jPanel2.setBackground(new java.awt.Color(22, 33, 62));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white), "Datos de Venta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setName(""); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fecha:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));

        txtVendedor.setBackground(new java.awt.Color(22, 33, 62));
        txtVendedor.setForeground(new java.awt.Color(255, 255, 255));
        txtVendedor.setBordeColorFocus(new java.awt.Color(255, 255, 255));
        txtVendedor.setBotonColor(new java.awt.Color(255, 255, 255));
        txtVendedor.setPlaceholder("");
        jPanel2.add(txtVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 350, -1));

        txtNumVenta.setBackground(new java.awt.Color(22, 33, 62));
        txtNumVenta.setForeground(new java.awt.Color(255, 255, 255));
        txtNumVenta.setBordeColorFocus(new java.awt.Color(255, 255, 255));
        txtNumVenta.setBotonColor(new java.awt.Color(255, 255, 255));
        txtNumVenta.setPlaceholder("");
        jPanel2.add(txtNumVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 100, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Vendedor:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("N° Venta:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tipo de Venta:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        txtFecha.setBackground(new java.awt.Color(22, 33, 62));
        txtFecha.setForeground(new java.awt.Color(255, 255, 255));
        txtFecha.setBordeColorFocus(new java.awt.Color(255, 255, 255));
        txtFecha.setBotonColor(new java.awt.Color(255, 255, 255));
        txtFecha.setPlaceholder("");
        jPanel2.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 150, -1));

        jPanel2.add(cmbTipoVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 260, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 510, 190));

        jPanel3.setBackground(new java.awt.Color(22, 33, 62));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white), "Datos del Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.setName(""); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscarClie.setBackground(new java.awt.Color(22, 33, 62));
        txtBuscarClie.setForeground(new java.awt.Color(255, 255, 255));
        txtBuscarClie.setBordeColorFocus(new java.awt.Color(255, 255, 255));
        txtBuscarClie.setBotonColor(new java.awt.Color(255, 255, 255));
        txtBuscarClie.setPlaceholder("");
        jPanel3.add(txtBuscarClie, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 110, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nombre:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Buscar Cliente:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        txtNombre.setBackground(new java.awt.Color(22, 33, 62));
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.setBordeColorFocus(new java.awt.Color(255, 255, 255));
        txtNombre.setBotonColor(new java.awt.Color(255, 255, 255));
        txtNombre.setPlaceholder("");
        jPanel3.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 310, -1));

        btnBuscarClie.setBackground(new java.awt.Color(26, 26, 46));
        btnBuscarClie.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarClie.setText("Buscar");
        btnBuscarClie.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(233, 69, 96)));
        btnBuscarClie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClieActionPerformed(evt);
            }
        });
        jPanel3.add(btnBuscarClie, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 90, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 440, 190));

        btnAgregar.setBackground(new java.awt.Color(26, 26, 46));
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(233, 69, 96)));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 292, 150, 60));

        jPanel4.setBackground(new java.awt.Color(22, 33, 62));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white), "Datos del articulo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.setName(""); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Precio Unitario:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        txtProducto.setBackground(new java.awt.Color(22, 33, 62));
        txtProducto.setForeground(new java.awt.Color(255, 255, 255));
        txtProducto.setBordeColorFocus(new java.awt.Color(255, 255, 255));
        txtProducto.setBotonColor(new java.awt.Color(255, 255, 255));
        txtProducto.setPlaceholder("");
        jPanel4.add(txtProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 290, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Producto:");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        txtCantidad.setBackground(new java.awt.Color(22, 33, 62));
        txtCantidad.setForeground(new java.awt.Color(255, 255, 255));
        txtCantidad.setBordeColorFocus(new java.awt.Color(255, 255, 255));
        txtCantidad.setBotonColor(new java.awt.Color(255, 255, 255));
        txtCantidad.setPlaceholder("");
        jPanel4.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 150, -1));

        btnBuscarPro.setBackground(new java.awt.Color(26, 26, 46));
        btnBuscarPro.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarPro.setText("Buscar");
        btnBuscarPro.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(233, 69, 96)));
        btnBuscarPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProActionPerformed(evt);
            }
        });
        jPanel4.add(btnBuscarPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 90, 40));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Stock:");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, -1, -1));

        txtPrecioUni.setBackground(new java.awt.Color(22, 33, 62));
        txtPrecioUni.setForeground(new java.awt.Color(255, 255, 255));
        txtPrecioUni.setBordeColorFocus(new java.awt.Color(255, 255, 255));
        txtPrecioUni.setBotonColor(new java.awt.Color(255, 255, 255));
        txtPrecioUni.setPlaceholder("");
        jPanel4.add(txtPrecioUni, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 190, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Cantidad:");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, -1, -1));

        txtStock.setBackground(new java.awt.Color(22, 33, 62));
        txtStock.setForeground(new java.awt.Color(255, 255, 255));
        txtStock.setBordeColorFocus(new java.awt.Color(255, 255, 255));
        txtStock.setBotonColor(new java.awt.Color(255, 255, 255));
        txtStock.setPlaceholder("");
        jPanel4.add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 140, -1));

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("IVA:      13%");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, 110, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 282, 800, 140));

        txtTotalVenta.setBackground(new java.awt.Color(22, 33, 62));
        txtTotalVenta.setForeground(new java.awt.Color(255, 255, 255));
        txtTotalVenta.setBordeColorFocus(new java.awt.Color(255, 255, 255));
        txtTotalVenta.setBotonColor(new java.awt.Color(255, 255, 255));
        txtTotalVenta.setPlaceholder("");
        jPanel1.add(txtTotalVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 610, 110, -1));

        btnGuardar.setBackground(new java.awt.Color(26, 26, 46));
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(233, 69, 96)));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 610, 150, 40));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Total:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 620, -1, -1));

        rSPanelShadow1.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(rSPanelShadow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -10, 1190, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnBuscarClieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClieActionPerformed
        //Abrir el formulario de cliente
        sesion.ventaCliente = "VoyDeVenta";
        frmClient cli = new frmClient(txtBuscarClie, txtNombre);
        cli.setVisible(true);
    }//GEN-LAST:event_btnBuscarClieActionPerformed

    private void btnBuscarProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProActionPerformed
        // Abrir el formulario de producto
        sesion.CProducto = "VoyDeVenta";//producto,   descripcion,    lote
        frmProduct men = new frmProduct(txtProducto, txtStock, txtPrecioUni);
        men.setVisible(true);
        
    }//GEN-LAST:event_btnBuscarProActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        //Agregar datos a la tabla
        int fact = Integer.parseInt(txtNumVenta.getText());
        String prod = txtProducto.getText();
        double prec = Double.parseDouble(txtPrecioUni.getText());
        int cant = Integer.parseInt(txtCantidad.getText().toString());
        if(prod.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un productos");
        }
        else if(cant == 0 || cant < 0)
        {
            JOptionPane.showMessageDialog(null, "La cantidad debe ser mayor a 0");
        }
        else if(txtCantidad.getText().equals("")) 
        {
            JOptionPane.showMessageDialog(null, "Debe ingresar la cantidad a comprar");
        }
        else
        {
            vnt.llenarTabla(fact, prod, prec, cant, tableVenta, txtTotalVenta);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        try{
            boolean valor;
            int idVenta = Integer.parseInt(txtNumVenta.getText().toString());
            int idTipo = cmbTipoVenta.getSelectedIndex();
            int idCliente = Integer.parseInt(txtBuscarClie.getText().toString());
            Date fecha = dateFormat.parse(txtFecha.getText());
            double total = Double.parseDouble(txtTotalVenta.getText().toString());
            valor = vnt.ingresarVenta(idVenta, idCliente, fecha, idTipo, total);
            if (valor == true)
            {
                boolean valor2;
                valor2 = vnt.ingresarDetalleVenta(tableVenta);
                if(valor2 == true)
                {
                    vnt.factura(idVenta);
                    JOptionPane.showMessageDialog(null, "Venta realizada correctamente");
                }
                else{
                    JOptionPane.showMessageDialog(null, "No se pudo ingresar el detalle de la venta");
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "No se pudo ingresar la venta");
            }
        }catch(ParseException ex)
        {
            Logger.getLogger(frmCompra.class.getName()).log(Level.SEVERE, null, ex);
           
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        vnt.eliminardetabla(tableVenta);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        txtBuscarClie.setText("");
        txtCantidad.setText("0");
        cmbTipoVenta.setSelectedIndex(0);
        txtNombre.setText("");
        txtProducto.setText("");
        txtStock.setText("");
        txtPrecioUni.setText("");
        txtTotalVenta.setText("");
        vnt.limpiarTabla(tableVenta);
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscarClie;
    private javax.swing.JButton btnBuscarPro;
    private javax.swing.JButton btnCancelar;
    private rojeru_san.RSButtonRiple btnCerrar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbTipoVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private rojeru_san.RSPanelShadow rSPanelShadow1;
    private javax.swing.JTable tableVenta;
    private rojeru_san.RSMTextFull txtBuscarClie;
    private rojeru_san.RSMTextFull txtCantidad;
    private rojeru_san.RSMTextFull txtFecha;
    private rojeru_san.RSMTextFull txtNombre;
    private rojeru_san.RSMTextFull txtNumVenta;
    private rojeru_san.RSMTextFull txtPrecioUni;
    private rojeru_san.RSMTextFull txtProducto;
    private rojeru_san.RSMTextFull txtStock;
    private rojeru_san.RSMTextFull txtTotalVenta;
    private rojeru_san.RSMTextFull txtVendedor;
    // End of variables declaration//GEN-END:variables
}
